"""Add MCP Telemetry

Revision ID: 06e3f3665f7e
Revises: 3f560ab0b0af
Create Date: 2026-06-06 15:56:35.719945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e3f3665f7e'
down_revision: Union[str, None] = '3f560ab0b0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_telemetry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('memory_count', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_telemetry_created_at'), 'mcp_telemetry', ['created_at'], unique=False)
    op.create_index(op.f('ix_mcp_telemetry_id'), 'mcp_telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_telemetry_project_id'), 'mcp_telemetry', ['project_id'], unique=False)
    op.create_index(op.f('ix_mcp_telemetry_tool_name'), 'mcp_telemetry', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_telemetry_tool_name'), table_name='mcp_telemetry')
    op.drop_index(op.f('ix_mcp_telemetry_project_id'), table_name='mcp_telemetry')
    op.drop_index(op.f('ix_mcp_telemetry_id'), table_name='mcp_telemetry')
    op.drop_index(op.f('ix_mcp_telemetry_created_at'), table_name='mcp_telemetry')
    op.drop_table('mcp_telemetry')
    # ### end Alembic commands ###
