from pydantic import BaseModel, Field

class AIResponse(BaseModel):
    provider: str = Field(..., description="The name of the provider used (e.g. 'openai')")
    model: str = Field(..., description="The specific model used (e.g. 'gpt-4o')")
    content: str = Field(..., description="The actual text content generated by the AI")
    tokens_used: int = Field(0, description="Total tokens used (prompt + completion)")
    latency_ms: float = Field(..., description="Time taken to generate the response in milliseconds")
    fallback_used: bool = Field(False, description="Whether this response was the result of a fallback mechanism")
